{% set name = "iso-codes" %}
{% set version = "4.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/iso-codes-{{ version }}/iso-codes-iso-codes-{{ version }}.tar.gz
  sha256: 6a321921b35b0ac73796f3b4ae41b29abaa523a01b0313313aa1d539c80ccfa0

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - make
    - python
    - pkg-config
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/share/xml/iso-codes/iso_3166.xml

about:
  home: https://salsa.debian.org/iso-codes-team/iso-codes
  license: LGPL-2.1-only
  license_family: GPL2
  license_file: COPYING
  summary: This project provides lists of various ISO standards (countries, languages, language scripts, and currency names) in one place. It also provides their translations in gettext .po format.

extra:
  recipe-maintainers:
    - izahn
