schema_version: 1

context:
  version: "4.20.1"

package:
  name: iso-codes
  version: ${{ version }}

source:
  url: https://salsa.debian.org/iso-codes-team/iso-codes/-/archive/v${{ version }}/iso-codes-v${{ version }}.tar.gz
  sha256: ff7c0d28975dc83e8975c1c815d3bb7371a4130ae90e3dc93508de2bf1939010

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - pkg-config
    - autoconf
    - automake
    - python >=3.10
  host:
    - libtool

tests:
  - script:
      - test -f ${PREFIX}/share/xml/iso-codes/iso_3166.xml

about:
  license: LGPL-2.1-only
  license_file: COPYING
  summary: This project provides lists of various ISO standards (countries, languages, language scripts, and currency names) in one place. It also provides their translations in gettext .po format.
  homepage: https://salsa.debian.org/iso-codes-team/iso-codes

extra:
  recipe-maintainers:
    - izahn
